# Fails when the third-party notices name another system's files (they ship
# with the app: the files they name must be the ones it carries).
#   cmake -DNOTICES=<build>/installer/THIRD-PARTY-NOTICES.txt -DSYSTEM=<Windows|Darwin|Linux> -P CheckNotices.cmake
if(NOT EXISTS "${NOTICES}")
    message(FATAL_ERROR "No notices at '${NOTICES}' (configure the build first)")
endif()
file(READ "${NOTICES}" text)
if(SYSTEM STREQUAL "Windows")
    set(foreign "\\.dylib|\\.so[ .]|Contents/Frameworks")
    set(own "Qt6\\*\\.dll")
elseif(SYSTEM STREQUAL "Darwin")
    set(foreign "\\.dll|\\.so[ .]|Visual C\\+\\+")
    set(own "Contents/Frameworks")
else()
    set(foreign "\\.dll|\\.dylib|Visual C\\+\\+|Contents/Frameworks")
    set(own "libQt6")
endif()
string(REGEX MATCH "[^\n]*(${foreign})[^\n]*" wrong "${text}")
if(wrong)
    message(FATAL_ERROR "The notices name another system's files (${SYSTEM}): ${wrong}")
endif()
if(NOT text MATCHES "${own}")
    message(FATAL_ERROR "The notices do not name this system's Qt files (${SYSTEM}): expected '${own}'")
endif()
message(STATUS "notices: name ${SYSTEM}'s own files")
